on: [push]
name: ashSecurityHeaders
jobs:
  pluginTemplate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: ojs
            php-version: 8.1
            database: mysql
          - application: ojs
            php-version: 7.4
            database: mysql
          - application: ojs
            php-version: 8.1
            database: pgsql
          - application: ojs
            php-version: 7.4
            database: pgsql

    name: pluginTemplate
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
         node_version: 20
         branch: main
         repository: pkp
         plugin: true

